@baseUrl = http://localhost:3000

### RecadosController

# @name RecadosController
GET {{baseUrl}}/recados/5

### RecadosController

# @name RecadosController
GET {{baseUrl}}/recados

### RecadosController

# @name RecadosController
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "recado": "Este é o recado que estou enviando.",
    "nova_chave": "Outro valor."
}