@baseUrl = http://localhost:3000

### RecadosController

# @name RecadosController
GET {{baseUrl}}/recados/2

### RecadosController

# @name RecadosController
GET {{baseUrl}}/recados/
?limit=15
&offset=2

### RecadosController

# @name RecadosController
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "NOVO recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2026-06-20T15:03:51.760Z"
  }

### RecadosController

# @name RecadosController
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

  {
    "texto": "ATUALIZAR recado",
    "de": "Joana",
    "para": "João",
    "lido": true,
    "data": "2026-06-20T15:03:51.760Z"
  }

### RecadosController

# @name RecadosController
DELETE {{baseUrl}}/recados/10