@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### AppControllerExample

# @name AppControllerExample
GET {{baseUrl}}/home/example

### ConceitosManualController

# @name ConceitosManualController
GET {{baseUrl}}/conceitos-manual
